### ISSUE TITLE
":ref: `access`" lacks the actual link

### ISSUE THREAD

**Issue by luixxiul** [cryptpad/documentation#17]
On `user_guide/apps/general.rst`, ":ref: `access`" lacks the actual link to `access`:

https://github.com/cryptpad/documentation/blob/4d3729392c768a7a069b5d9eeca34d1c7b9d6d3f/user_guide/apps/general.rst?plain=1#L31

**Comment by davidbenque** [comment]
This is an RST reference links that points to the [Access anchor](https://github.com/cryptpad/documentation/blob/4d3729392c768a7a069b5d9eeca34d1c7b9d6d3f/user_guide/share_and_access.rst?plain=1#L149)

**Comment by luixxiul** [comment]
Shouldn't it not <pre>`:ref:`access` <access>`</pre>, in the same way as <pre>:ref:`password <passwords>`</pre> on the same line?

**Comment by luixxiul** [comment]
Ah, I understand the issue is that <pre>:ref:`access`</pre> should not be something like <pre>:ref:`access_localized_in_another_language`</pre> because there is not actually anchor named `access_localized_in_another_language`.

So when you localize, you always need to write like this: <pre>:ref:`access_localized_in_another_language <access>`</pre>

Otherwise, the anchor link would point to `#access_localized_in_another_language`, which does not exist.

**Comment by luixxiul** [comment]
Here is a link to the page for localizing it on Weblate: https://weblate.cryptpad.fr/translate/user-guide/application-general/ja/?checksum=278d2e66caf467aa&sort_by=-priority,position

**Comment by davidbenque** [comment]
I believe you should just leave the `:ref:` link as is. As long as you translate the first heading after the anchor, the link text should be localized

**Comment by luixxiul** [comment]
I am not quite sure if this is the case, as the anchor link text does not seem to be localized, for example, here: https://docs.cryptpad.org/ja/user_guide/user_account.html#guest-user

**Comment by davidbenque** [comment]
I think in the example you showed it does not work because no `guest-user` anchor is defined

If you check https://docs.cryptpad.org/ja/FAQ.html#rich-text-document-import-export you can see that although the text isn't translated yet, the ref link ``:ref:`app_rich_text` `` correctly produces a link where the text is "リッチテキスト"  which is the first heading after the [anchor definition](https://github.com/cryptpad/documentation/blob/4d3729392c768a7a069b5d9eeca34d1c7b9d6d3f/user_guide/apps/richtext.rst?plain=1#L1)

**Comment by luixxiul** [comment]
That totally makes sense! Thanks for the follow-up :smile:
